### ISSUE TITLE
Image preprocessing

### ISSUE THREAD

**Issue by 1938254962** [HaoliangZhou/Dual-ATME#1]
Hello author, can you provide the code for image preprocessing? These include face alignment and cropping, manual extraction and reorganization of ROI regions, and extraction of optical flow features

**Comment by HaoliangZhou** [comment]
Hello,
Due to the code in this part not being properly organized yet, we are unable to release it at the moment. 
However, you may follow the steps outlined in Section 3.2 of the paper for face processing, which should not be too difficult. 

The steps include face alignment, face landmark detection based on Dlib, and cropping of ROIs based on these landmarks. As for optical flow calculation, we utilized the TVL1 algorithm.

Best regards.
